"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { CLOSURE_TEMPLATES } from "@noghost/config/copy";
import { validateDateProposal } from "@noghost/logic";
import { requireMember } from "@/lib/member";
import { supabaseServer } from "@/lib/supabase";
import { checkTone, toneCheckConfigured } from "@/lib/tone";
import {
  ACCEPTED_AUDIO,
  MAX_BYTES,
  MAX_DURATION_MS,
  baseMimeType,
  extensionFor,
} from "@/lib/voice";

/**
 * Everything a member can do inside a chat — spec §7.2 and §6.3.
 *
 * Every action re-checks `requireMember()`: the layout guard protects
 * rendering, not a POST endpoint. None of them is the authorisation boundary
 * either — sending a message is allowed by one RLS policy pinned to an open
 * chat you belong to, and the date and closure paths go through RPCs that
 * re-validate in SQL.
 */

export interface ChatActionState {
  error?: string;
  /** A tone-check rewrite, offered rather than enforced (§6.6). */
  suggestion?: string;
  /** Set once a close has actually happened, so the sheet can stand down. */
  closed?: boolean;
  /**
   * Echoes the `token` a voice send was given, once that send has landed.
   *
   * The composer needs to know that *this* recording is gone, not that some
   * recording once sent — otherwise a second note recorded after a successful
   * first one would be treated as already sent. Comparing the echo to the
   * recording's own id makes "has it been sent" a derived value instead of
   * something an effect has to notice and clear.
   */
  sentToken?: string;
}

const CLOSED = "That chat is closed. Nothing more can be sent.";

export async function sendMessage(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  const member = await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const body = String(formData.get("body") ?? "").trim();

  if (!chatId) return { error: "That chat isn't there any more." };
  if (!body) return {};
  if (body.length > 4000) return { error: "That's longer than a message can be." };

  const supabase = await supabaseServer();

  /*
   * A direct insert. `sender writes into an open chat` is the only policy that
   * permits it, and it checks three things in SQL: the sender is the caller,
   * the kind is text or voice, and the chat is still open. `.select()` matters
   * — with no matching row RLS returns zero rows and no error, so without it a
   * message into a closed chat would look like it sent.
   */
  const { data, error } = await supabase
    .from("messages")
    .insert({ chat_id: chatId, sender_id: member.id, kind: "text", body })
    .select("id");

  if (error) {
    console.error(`[chat] send ${chatId}: ${error.message}`);
    return { error: "That didn't send. Try again." };
  }
  if (!data || data.length === 0) return { error: CLOSED };

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  return {};
}

/**
 * A voice note — spec §7.2, and the reason §5's `voice-notes` bucket exists.
 *
 * The audio travels *through* this action rather than going straight from the
 * browser to Storage, and that is the security decision in the whole feature.
 * The bucket's policy authorises a write by the first path segment
 * (`is_chat_participant(<folder>)`), so whoever names the folder decides which
 * chat the object belongs to. A client-supplied path would let a member move a
 * note between two chats they are both in — attaching one partner's recording
 * to a conversation with the other. Here the server builds the path from the
 * chat id it was given and a fresh uuid, so that class of mistake cannot be
 * expressed.
 *
 * The upload still runs on the member's own session, not a service client: the
 * storage policy remains the thing that decides whether they may write into
 * this chat, and this code never gets to overrule it.
 */
export async function sendVoiceNote(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  const member = await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const audio = formData.get("audio");
  const durationMs = Number(formData.get("durationMs") ?? 0);
  // Opaque to the server: generated by the composer, returned unchanged, and
  // never written anywhere.
  const token = String(formData.get("token") ?? "");

  if (!chatId) return { error: "That chat isn't there any more." };
  if (!(audio instanceof File) || audio.size === 0) return { error: "There was nothing to send." };
  if (audio.size > MAX_BYTES) return { error: "That recording is too large to send." };

  const mime = baseMimeType(audio.type);
  const extension = extensionFor(mime);
  // Checked here as well as by the bucket so the refusal is a sentence rather
  // than a storage error, and so a browser recording something exotic finds out
  // before the upload rather than after it.
  if (!extension || !ACCEPTED_AUDIO.includes(mime as (typeof ACCEPTED_AUDIO)[number])) {
    return { error: "That audio format isn't one we can store." };
  }

  // Clamped, not rejected: the duration is the browser's stopwatch and only
  // feeds a label. The column's own check would reject anything over 300000.
  const duration = Number.isFinite(durationMs)
    ? Math.max(0, Math.min(Math.round(durationMs), MAX_DURATION_MS))
    : 0;

  const supabase = await supabaseServer();
  const path = `${chatId}/${crypto.randomUUID()}.${extension}`;

  const { error: uploadError } = await supabase.storage
    .from("voice-notes")
    .upload(path, audio, { contentType: mime, upsert: false });

  if (uploadError) {
    console.error(`[chat] voice upload ${chatId}: ${uploadError.message}`);
    // The bucket has no policy for a chat you are not in, so RLS surfaces here
    // rather than at the insert.
    if (/row-level security|not authorized/i.test(uploadError.message)) {
      return { error: "That chat isn't yours." };
    }
    return { error: "That didn't send. Try again." };
  }

  const { data, error } = await supabase
    .from("messages")
    .insert({
      chat_id: chatId,
      sender_id: member.id,
      kind: "voice",
      voice_path: path,
      voice_duration_ms: duration,
    })
    .select("id");

  /*
   * Upload first, then insert — so a failure leaves an object with no message
   * rather than a message with no audio. The orphan is cleaned up here, and the
   * ordering is what makes that possible: a broken player in a conversation is
   * not something the reader can fix, and a stray object in a private bucket is
   * not something they can see.
   */
  if (error || !data || data.length === 0) {
    const { error: cleanupError } = await supabase.storage.from("voice-notes").remove([path]);
    if (cleanupError) console.error(`[chat] orphan ${path}: ${cleanupError.message}`);
    if (error) {
      console.error(`[chat] voice message ${chatId}: ${error.message}`);
      return { error: "That didn't send. Try again." };
    }
    return { error: CLOSED };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  return { sentToken: token };
}

export async function proposeDate(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const day = String(formData.get("day") ?? "");
  const time = String(formData.get("time") ?? "");
  const placeName = String(formData.get("placeName") ?? "").trim();
  const placeNote = String(formData.get("placeNote") ?? "").trim();

  if (!chatId) return { error: "That chat isn't there any more." };
  if (!day || !time) return { error: "Pick a day and a time." };

  /*
   * Assembled as a local wall-clock string and left to the browser's zone.
   * `new Date("2026-08-20T19:00")` — no trailing Z — is parsed as local time,
   * which is what someone typing "7pm" means. Appending Z would move the date
   * by hours and silently propose the wrong evening.
   */
  const scheduledFor = new Date(`${day}T${time}`);
  if (Number.isNaN(scheduledFor.getTime())) return { error: "That's not a real time." };

  const now = new Date().toISOString();
  const check = validateDateProposal(
    { scheduledFor: scheduledFor.toISOString(), placeName, placeNote },
    now,
  );
  if (!check.ok) return { error: check.message };

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("propose_date", {
    p_chat_id: chatId,
    p_scheduled_for: scheduledFor.toISOString(),
    p_place_name: placeName,
    p_place_note: placeNote || null,
  });

  if (error) {
    console.error(`[chat] propose_date ${chatId}: ${error.message}`);
    // The RPC re-checks the same 2-hour and 14-day window in SQL and says so
    // in words a member can read, so those messages pass through.
    if (/at least 2 hours|within the next 14 days/i.test(error.message)) {
      return { error: error.message.replace(/^.*?:\s*/, "") };
    }
    if (/not open|closed/i.test(error.message)) return { error: CLOSED };
    return { error: "That didn't send. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  return {};
}

export async function respondToDate(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const dateId = String(formData.get("dateId") ?? "");
  const confirm = String(formData.get("confirm") ?? "") === "yes";

  if (!dateId) return { error: "That plan isn't there any more." };

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("respond_to_date", {
    p_date_id: dateId,
    p_confirm: confirm,
  });

  if (error) {
    console.error(`[chat] respond_to_date ${dateId}: ${error.message}`);
    if (/other person confirms/i.test(error.message)) {
      return { error: "They proposed it, so it's theirs to confirm — not yours." };
    }
    if (/already answered/i.test(error.message)) {
      return { error: "That's already been answered. Reload to see where it landed." };
    }
    return { error: "That didn't save. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  return {};
}

/**
 * Answering the post-date check-in — spec §6.3.
 *
 * `answer_checkin` does all the deciding in one transaction: it upserts the
 * caller's own row, reads the partner's, and then either closes the chat or
 * restarts the fuse for a fresh seven days. Deliberately not split across the
 * client: a member must never be able to observe the partner's answer by
 * inspecting what this action returns, so the RPC's return value is discarded
 * rather than surfaced.
 */
export async function answerCheckin(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const dateId = String(formData.get("dateId") ?? "");
  const answer = String(formData.get("answer") ?? "");

  if (!dateId) return { error: "That check-in isn't there any more." };
  if (answer !== "continue" && answer !== "close") {
    return { error: "That isn't an answer we can record." };
  }

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("answer_checkin", {
    p_date_id: dateId,
    p_answer: answer,
  });

  if (error) {
    console.error(`[chat] answer_checkin ${dateId}: ${error.message}`);
    if (/not found/i.test(error.message)) {
      return { error: "That check-in isn't yours to answer." };
    }
    return { error: "That didn't save. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  /*
   * Intentionally empty. `answer_checkin` returns "closed" | "continued" |
   * "pending", and returning that here would tell the first person to answer
   * exactly what the second one chose — the one thing §6.3 says neither of them
   * may learn. The page re-reads the chat's own state instead.
   */
  return {};
}

/**
 * Found Someone — spec §6.5.
 *
 * Proposing is cheap and reversible; confirming ends the season for both of
 * them. So the two halves are separate actions, and `respond_graduation` is the
 * one that does everything: it closes this chat, closes every *other* open chat
 * either of them has with the "met someone" note (§9.2 closure_03), flips both
 * accounts to `found_someone`, and opens an exit survey each.
 */
export async function proposeGraduation(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  if (!chatId) return { error: "That chat isn't there any more." };

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("propose_graduation", { p_chat_id: chatId });

  if (error) {
    console.error(`[chat] propose_graduation ${chatId}: ${error.message}`);
    if (/not your chat/i.test(error.message)) return { error: "That chat isn't yours." };
    /*
     * 0013 refuses a second ask. Only a replayed POST can reach this — the
     * button is gone once asked — and the honest answer is the one the UI
     * already gives: your ask is in. Reporting a failure here would also be a
     * distinguishable outcome, which is what §6.5 spends this whole mechanic
     * avoiding.
     */
    if (/already asked/i.test(error.message)) {
      revalidatePath(`/chats/${chatId}`);
      return {};
    }
    return { error: "That didn't send. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  return {};
}

export async function respondGraduation(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const graduationId = String(formData.get("graduationId") ?? "");
  const confirm = String(formData.get("confirm") ?? "") === "yes";

  if (!graduationId) return { error: "That question isn't there any more." };

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("respond_graduation", {
    p_graduation_id: graduationId,
    p_confirm: confirm,
  });

  if (error) {
    console.error(`[chat] respond_graduation ${graduationId}: ${error.message}`);
    if (/other person confirms/i.test(error.message)) {
      return { error: "You asked — it's theirs to answer." };
    }
    /*
     * Named precisely, like the 0009 and 0011 cases. Without
     * 0012_status_writes_by_rpc.sql the profiles trigger reverts the
     * `found_someone` write in the same statement, so the graduation half-lands:
     * chats close but neither account graduates.
     */
    if (/status is changed by|is of type member_status/i.test(error.message)) {
      return {
        error:
          "This database hasn't had 0012_status_writes_by_rpc.sql applied, so graduating " +
          "can't set both accounts. Apply it and try again.",
      };
    }
    return { error: "That didn't save. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  revalidatePath("/tonight");

  /*
   * A confirm ends the season, so it leaves the chat for the screen that says so
   * and carries the exit survey. Only the person who just said yes is moved —
   * the proposer finds out on their next page load, because their account is now
   * `found_someone` and `/tonight` sends them to the same place.
   */
  if (confirm) redirect("/found-someone");

  /*
   * A decline deliberately returns nothing. §6.5 makes declining private, so the
   * response must not let the proposer distinguish "declined" from "not answered
   * yet" — and the read layer drops the declined row for the same reason.
   */
  return {};
}

type TemplateId = (typeof CLOSURE_TEMPLATES)[number]["id"];
const TEMPLATE_IDS: readonly string[] = CLOSURE_TEMPLATES.map((template) => template.id);
const isTemplateId = (value: string): value is TemplateId => TEMPLATE_IDS.includes(value);

/**
 * Closing kindly — spec §6.3 and §9.2.
 *
 * A template is required and a personal line is optional. The tone check runs
 * on the line only, and it **offers** a rewrite rather than refusing the close:
 * §6.6 is explicit that a member is never blocked from ending a conversation.
 * Submitting again with the same line goes through — the second submit carries
 * `acknowledged`, which is the member choosing to keep their words.
 */
export async function closeChat(
  _prev: ChatActionState,
  formData: FormData,
): Promise<ChatActionState> {
  await requireMember();

  const chatId = String(formData.get("chatId") ?? "");
  const templateId = String(formData.get("templateId") ?? "");
  const personalLine = String(formData.get("personalLine") ?? "").trim();
  const acknowledged = String(formData.get("acknowledged") ?? "") === "yes";

  if (!chatId) return { error: "That chat isn't there any more." };
  /*
   * Narrowed, not just membership-tested. `close_chat`'s typed signature wants
   * one of §9.2's six ids, and a guard that only returns a boolean leaves the
   * value as `string` — so the RPC call would either not compile or need a cast
   * that throws the check away.
   */
  if (!isTemplateId(templateId)) {
    return { error: "Pick how you want to say it." };
  }
  if (personalLine.length > 500) {
    return { error: "Keep the personal line under 500 characters." };
  }

  /*
   * `null` means the check did not run — §5's own note on the column. A
   * template-only closure skips it (there is no line to check), and so does a
   * missing API key or an outage, which is why the value is nullable rather
   * than defaulting to `true`.
   */
  let tonePassed: boolean | null = null;

  if (personalLine) {
    const result = await checkTone(personalLine);
    tonePassed = toneCheckConfigured() ? result.pass : null;

    if (!result.pass && !acknowledged) {
      return { suggestion: result.suggestion };
    }
  }

  const supabase = await supabaseServer();
  const { error } = await supabase.rpc("close_chat", {
    p_chat_id: chatId,
    p_template_id: templateId,
    p_personal_line: personalLine || null,
    p_tone_check_passed: tonePassed,
  });

  if (error) {
    console.error(`[chat] close_chat ${chatId}: ${error.message}`);
    if (/not open|closed|state/i.test(error.message)) return { error: CLOSED };
    return { error: "That didn't send. Try again." };
  }

  revalidatePath(`/chats/${chatId}`);
  // The list lives at /inbox now; /chats is only a redirect.
  revalidatePath("/inbox");
  return { closed: true };
}
